# Generated by Django 3.2.18 on 2024-05-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_auto_20240429_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='JWTUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hashed_password', models.CharField(max_length=255)),
                ('disabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='KnowledgeBaseViewerModel',
        ),
        migrations.DeleteModel(
            name='QueryEndpoint',
        ),
        migrations.AddField(
            model_name='jwtuser',
            name='scopes',
            field=models.ManyToManyField(to='Web.Scope'),
        ),
    ]
