# Generated by Django 3.2.18 on 2024-05-02 02:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_auto_20240502_0155'),
    ]

    operations = [
        migrations.AddField(
            model_name='scope',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scope',
            name='description',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scope',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
