# Generated by Django 4.2.11 on 2024-05-02 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Web", "0007_rename_hashed_password_jwtuser_password_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jwtuser",
            name="disabled",
        ),
        migrations.AddField(
            model_name="jwtuser",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
