# Generated by Django 3.2.18 on 2024-04-25 14:47

import autoslug.fields
from django.db import migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='knowledgebaseviewermodel',
            name='left_side_menu_title_slug',
            field=autoslug.fields.AutoSlugField(default=django.utils.timezone.now, editable=False, populate_from='left_side_menu_title'),
            preserve_default=False,
        ),
    ]
