# Generated by Django 3.2.18 on 2024-04-25 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0002_knowledgebaseviewermodel_left_side_menu_title_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledgebaseviewermodel',
            old_name='menu_active',
            new_name='status_active',
        ),
    ]
