# Generated by Django 3.2.18 on 2024-05-10 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0004_auto_20240429_0342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='queryendpoint',
            name='query_endpoint_type',
            field=models.CharField(choices=[('get', 'GET'), ('post', 'POST'), ('put', 'PUT'), ('delete', 'DELETE')], default='get', max_length=20, unique=True),
        ),
    ]
