# Generated by Django 3.2.18 on 2024-05-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0005_alter_queryendpoint_query_endpoint_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='queryendpoint',
            name='default_kb',
            field=models.URLField(default=False, unique=True),
        ),
    ]
