# Generated by Django 3.2.18 on 2024-05-12 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0008_auto_20240510_1840'),
    ]

    operations = [
        migrations.RenameField(
            model_name='knowledgebaseviewermodel',
            old_name='left_side_menu_title_slug',
            new_name='slug',
        ),
        migrations.AlterField(
            model_name='knowledgebaseviewermodel',
            name='display_column_first',
            field=models.CharField(help_text='The column that will be displayed when the page loads.', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='knowledgebaseviewermodel',
            name='display_column_fourth',
            field=models.CharField(blank=True, help_text='The column that will be displayed when the page loads.', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='knowledgebaseviewermodel',
            name='display_column_second',
            field=models.CharField(help_text='The column that will be displayed when the page loads.', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='knowledgebaseviewermodel',
            name='display_column_third',
            field=models.CharField(help_text='The column that will be displayed when the page loads.', max_length=150, unique=True),
        ),
    ]
