# Generated by Django 3.2.18 on 2024-05-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0009_auto_20240512_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebaseviewermodel',
            name='display_column_first',
            field=models.CharField(help_text='The column that will be displayed when the page loads.', max_length=150),
        ),
        migrations.AlterField(
            model_name='knowledgebaseviewermodel',
            name='display_column_fourth',
            field=models.CharField(blank=True, help_text='The column that will be displayed when the page loads.', max_length=150),
        ),
        migrations.AlterField(
            model_name='knowledgebaseviewermodel',
            name='display_column_second',
            field=models.CharField(help_text='The column that will be displayed when the page loads.', max_length=150),
        ),
        migrations.AlterField(
            model_name='knowledgebaseviewermodel',
            name='display_column_third',
            field=models.CharField(help_text='The column that will be displayed when the page loads.', max_length=150),
        ),
    ]
