# Generated by Django 3.2.18 on 2024-05-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Web', '0010_auto_20240512_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='knowledgebaseviewermodel',
            name='default_kb',
            field=models.BooleanField(default=False),
        ),
    ]
